/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Font;

/**
 *
 * @author Gonzalo
 */
public class JFrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrmMenu
     */
    public JFrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuAdminJugador = new javax.swing.JMenuItem();
        mnufiltrarjugador = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuAdminClub = new javax.swing.JMenuItem();
        mnuclubfiltrar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MnuAdminEntrenador = new javax.swing.JMenuItem();
        mnuEntrenadorListar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuContrato = new javax.swing.JMenuItem();
        mnuFiltrarContrato = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblMenu.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblMenu.setText("Menu ANFP");
        lblMenu.setName(""); // NOI18N
        lblMenu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblMenuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenu2.setText("Jugador");

        mnuAdminJugador.setText("Administrar Jugador");
        mnuAdminJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminJugadorActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdminJugador);

        mnufiltrarjugador.setText("Listar y Filtrar");
        mnufiltrarjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnufiltrarjugadorActionPerformed(evt);
            }
        });
        jMenu2.add(mnufiltrarjugador);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Club");

        mnuAdminClub.setText("Administrar Club");
        mnuAdminClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminClubActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAdminClub);

        mnuclubfiltrar.setText("Listar y Filtrar");
        mnuclubfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuclubfiltrarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuclubfiltrar);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Entrenador");

        MnuAdminEntrenador.setText("Administrar Entrenador");
        MnuAdminEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAdminEntrenadorActionPerformed(evt);
            }
        });
        jMenu3.add(MnuAdminEntrenador);

        mnuEntrenadorListar.setText("Listar y Filtar");
        mnuEntrenadorListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntrenadorListarActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEntrenadorListar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Contrato");

        mnuContrato.setText("Administrar Contrato");
        mnuContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuContratoActionPerformed(evt);
            }
        });
        jMenu4.add(mnuContrato);

        mnuFiltrarContrato.setText("Filtrar Contrato");
        mnuFiltrarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFiltrarContratoActionPerformed(evt);
            }
        });
        jMenu4.add(mnuFiltrarContrato);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(lblMenu)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAdminClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminClubActionPerformed
        // TODO add your handling code here:
        JFrmClub club=new JFrmClub();
        club.setVisible(true);
    }//GEN-LAST:event_mnuAdminClubActionPerformed

    private void mnuclubfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuclubfiltrarActionPerformed
        // TODO add your handling code here:
        JFrmClubList clubl=new JFrmClubList();
        clubl.setVisible(true);
    }//GEN-LAST:event_mnuclubfiltrarActionPerformed

    private void lblMenuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblMenuAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblMenuAncestorAdded

    private void mnufiltrarjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnufiltrarjugadorActionPerformed
        // TODO add your handling code here:
        JFrmJugadorList jugador1=new JFrmJugadorList();
        jugador1.setVisible(true);
    }//GEN-LAST:event_mnufiltrarjugadorActionPerformed

    private void MnuAdminEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAdminEntrenadorActionPerformed
        // TODO add your handling code here:
        JFrmEntrenador entrenador=new JFrmEntrenador();
        entrenador.setVisible(true);
    }//GEN-LAST:event_MnuAdminEntrenadorActionPerformed

    private void mnuEntrenadorListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntrenadorListarActionPerformed
        // TODO add your handling code here:
        JFrmEntrenadorList entrenador1=new JFrmEntrenadorList();
        entrenador1.setVisible(true);
    }//GEN-LAST:event_mnuEntrenadorListarActionPerformed

    private void mnuContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuContratoActionPerformed
        // TODO add your handling code here:
        JFrmContrato contrato=new JFrmContrato();
        contrato.setVisible(true);
    }//GEN-LAST:event_mnuContratoActionPerformed

    private void mnuFiltrarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFiltrarContratoActionPerformed
        // TODO add your handling code here:
        JFrmContratoList contrato1=new JFrmContratoList();
        contrato1.setVisible(true);
    }//GEN-LAST:event_mnuFiltrarContratoActionPerformed

    private void mnuAdminJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminJugadorActionPerformed
        // TODO add your handling code here:
        JFrmJugador jugador=new JFrmJugador();
        jugador.setVisible(true);
    }//GEN-LAST:event_mnuAdminJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuAdminEntrenador;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JMenuItem mnuAdminClub;
    private javax.swing.JMenuItem mnuAdminJugador;
    private javax.swing.JMenuItem mnuContrato;
    private javax.swing.JMenuItem mnuEntrenadorListar;
    private javax.swing.JMenuItem mnuFiltrarContrato;
    private javax.swing.JMenuItem mnuclubfiltrar;
    private javax.swing.JMenuItem mnufiltrarjugador;
    // End of variables declaration//GEN-END:variables
}
